# Generated by Django 4.2.7 on 2023-12-09 15:53

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("taskapp", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="project",
            name="members",
        ),
        migrations.RemoveField(
            model_name="project",
            name="owner",
        ),
        migrations.RemoveField(
            model_name="tag",
            name="tasks",
        ),
        migrations.RemoveField(
            model_name="task",
            name="assignee",
        ),
        migrations.RemoveField(
            model_name="task",
            name="project",
        ),
        migrations.RemoveField(
            model_name="timelog",
            name="task",
        ),
        migrations.RemoveField(
            model_name="timelog",
            name="user",
        ),
        migrations.RemoveField(
            model_name="userprofile",
            name="user",
        ),
        migrations.DeleteModel(
            name="Comment",
        ),
        migrations.DeleteModel(
            name="Project",
        ),
        migrations.DeleteModel(
            name="Tag",
        ),
        migrations.DeleteModel(
            name="Task",
        ),
        migrations.DeleteModel(
            name="TimeLog",
        ),
        migrations.DeleteModel(
            name="UserProfile",
        ),
    ]
