# Generated by Django 4.2.7 on 2023-12-11 21:55

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("taskapp", "0007_userprofile"),
    ]

    operations = [
        migrations.RenameField(
            model_name="userprofile",
            old_name="selected_organisation",
            new_name="selected_organization",
        ),
    ]
