# Generated by Django 4.2.7 on 2023-12-16 11:47

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        (
            "taskapp",
            "0008_rename_selected_organisation_userprofile_selected_organization",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="task",
            name="collaborators",
            field=models.ManyToManyField(
                blank=True,
                related_name="task_collaborators",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
