# Generated by Django 4.2.7 on 2023-12-16 17:04

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("taskapp", "0010_organizationinvitation"),
    ]

    operations = [
        migrations.AddField(
            model_name="organizationinvitation",
            name="token_expiry",
            field=models.DateTimeField(null=True),
        ),
    ]
