# Generated by Django 4.2.7 on 2023-12-20 22:50

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("taskapp", "0013_rename_is_admin_organizationmember_is_owner"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="organization",
            name="users",
        ),
        migrations.RemoveField(
            model_name="organizationmember",
            name="is_owner",
        ),
        migrations.AddField(
            model_name="organizationmember",
            name="role",
            field=models.CharField(
                choices=[("OWNER", "Owner"), ("ADMIN", "Admin"), ("MEMBER", "Member")],
                default="MEMBER",
                max_length=10,
            ),
        ),
    ]
