# Generated by Django 4.2.7 on 2023-12-20 22:52

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("taskapp", "0014_remove_organization_users_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="organizationmember",
            name="role",
            field=models.CharField(
                choices=[("OWNER", "Owner"), ("ADMIN", "Admin"), ("MEMBER", "Member")],
                max_length=10,
            ),
        ),
    ]
