# Generated by Django 4.2.7 on 2023-12-24 16:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("taskapp", "0016_task_owner_alter_task_assigned_to"),
    ]

    operations = [
        migrations.CreateModel(
            name="TaskChangeRequest",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "change_type",
                    models.CharField(
                        choices=[
                            ("OWNER", "Owner Change"),
                            ("ASSIGNED_TO", "Assigned To Change"),
                        ],
                        max_length=20,
                    ),
                ),
                ("is_accepted", models.BooleanField(default=False)),
                ("request_date", models.DateTimeField(auto_now_add=True)),
                (
                    "new_user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="task_change_requests",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "task",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="taskapp.task"
                    ),
                ),
            ],
        ),
    ]
