# Generated by Django 4.2.7 on 2023-12-24 18:24

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("taskapp", "0017_taskchangerequest"),
    ]

    operations = [
        migrations.AddField(
            model_name="taskchangerequest",
            name="is_archived",
            field=models.BooleanField(default=False),
        ),
    ]
