# Generated by Django 4.2.7 on 2023-12-24 18:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("taskapp", "0018_taskchangerequest_is_archived"),
    ]

    operations = [
        migrations.AlterField(
            model_name="taskchangerequest",
            name="task",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="taskapp.task",
            ),
        ),
    ]
