# Generated by Django 4.2.7 on 2023-12-24 19:09

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("taskapp", "0019_alter_taskchangerequest_task"),
    ]

    operations = [
        migrations.AddField(
            model_name="taskchangerequest",
            name="task_title",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
