# Generated by Django 4.2.7 on 2024-02-05 18:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("taskapp", "0025_alter_notification_related_id"),
    ]

    operations = [
        migrations.AddField(
            model_name="taskchangerequest",
            name="current_user",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="task_change_requests_current_user",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
