# Generated by Django 4.2.7 on 2024-02-06 19:32

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("taskapp", "0026_taskchangerequest_current_user"),
    ]

    operations = [
        migrations.AddField(
            model_name="notification",
            name="allow_confirm",
            field=models.BooleanField(default=False),
        ),
    ]
