# Generated by Django 4.2.7 on 2024-02-13 22:48

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("taskapp", "0029_task_project"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="project",
            name="collaborators",
        ),
        migrations.RemoveField(
            model_name="project",
            name="owner",
        ),
    ]
