# Generated by Django 4.2.7 on 2024-02-13 23:01

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("taskapp", "0030_remove_project_collaborators_remove_project_owner"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="task",
            name="owner",
        ),
        migrations.DeleteModel(
            name="TaskChangeRequest",
        ),
    ]
